alias ssh='autossh'
alias trw='tmux rename-window'
alias trs='tmux rename-session'
alias aa='sudo apt-get update'
alias ad='sudo apt-get update && sudo apt-get dist-upgrade'
alias au='sudo apt-get update && sudo apt-get upgrade -y'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ......='cd ../../../../..'
alias lla='ls -la'
alias llh='ls -lh'
alias llah='ls -lha'
alias llha='ls -lha'
alias datewest='TZ='America/Los_Angeles' date'
alias dateeast='TZ='America/New_York' date'
alias dateeuro='TZ='America/Amsterdam' date'
alias ec2start='aws ec2 start-instances --instance-ids '
alias ec2startva='aws ec2 --profile=va start-instances --instance-ids '
alias ec2startoh='aws ec2 --profile=oh start-instances --instance-ids '
alias ec2startca='aws ec2 --profile=ca start-instances --instance-ids '
alias ec2startor='aws ec2 --profile=or start-instances --instance-ids '
alias ec2stop='aws ec2 stop-instances --instance-ids '
alias ec2stopva='aws ec2 --profile=va stop-instances --instance-ids '
alias ec2stopoh='aws ec2 --profile=oh stop-instances --instance-ids '
alias ec2stopca='aws ec2 --profile=ca stop-instances --instance-ids '
alias ec2stopor='aws ec2 --profile=or stop-instances --instance-ids '
